config/routes.rb
Rails.application.routes.draw do
  root 'statics#index'
  get 'contacts', to: 'contacts#index'
  get 'contacts/thanks', to: 'contacts#thanks'
  resources :contacts, :only => [:index, :create]
  resources :blogs

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/static.rb
class Static < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :content, :user_id)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contact = Contact.new
  end

  def thanks
  end

  def create
    @contact = Contact.create(contact_params)
    if @contact.save
      redirect_to contacts_thanks_path
    else
      render 'index'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:title, :content, :email)
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def index
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= blog.user_id %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @blog.user_id %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/contacts/index.html.erb
<div class="content">
  <h1>お問い合わせフォーム</h1>
  <% if @contact.errors.any? %>
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @contact.errors.count %>件のエラーがあります。</h3>
      </div>
      <div class="panel-body">
        <% @contact.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
        <% end %>
      </div>
    </div>
  <% end %>
  <%= form_for(@contact) do |f| %>
  <div class="explanation">
    <div class="field">
      <p><i class="fa fa-pencil"></i><%= f.label :title %></p>
      <p><%= f.text_field :title, placeholder: 'タイトル記入' %></p>
    </div>
    <div class="field">
      <p><i class="fa fa-commenting-o"></i><%= f.label :body %></p>
      <p><%= f.text_area :body %></p>
    </div>
    <div class="field">
      <p><%= f.label :tel %></p>
      <p><%= f.text_field :tel %></p>
    </div>
    <div class="field">
      <%= f.submit class: "btn btn-primary" %>
      <%= link_to 'Back', root_path, class: "btn btn-default" %>
    </div>
  <% end %>
  </div>
</div>

app/views/contacts/thanks.html.erb
<div class="content">
  <div class="explanation">
    <h1>お問い合わせありがとうございます！</h1>
    <div class="btn">
      <%= link_to 'Back', root_path %>
    </div>
  </div>
</div

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width">
  <title>Achieve</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "bootstrap", media: "all", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="/assets/common.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-default">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="javascript:void(0)">Brand</a>
    </div>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
        <form class="navbar-form navbar-left">
            <input type="text" class="form-control col-lg-8" placeholder="Search">
        </form>
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Top', root_path %></li>
            <li><%= link_to 'Contact', contacts_path %></li>

        </ul>
    </div>
</div>
<div class="alert alert-info" role="alert">
  <p class="notice"><%= notice %></p>
</div>
<div class="alert alert-info" role="alert">
  <p><%= alert %></p>
</div>
<%= yield %>
<div class="page-top">
<a href="#" class="btn btn-info btn-fab btn-raised mdi-action-grade"><div class="ripple-wrapper"></div></a>
</div>
  </body>
</html>

app/views/statics/index.html.erb
<div class="jumbotron">
  <h1>Achieve</h1>
  <p>Achieveは達成できた！そんな思いを大切な人と共有するアプリ</p>
  <p><a class="btn btn-primary btn-lg" href="<%= new_blog_path %>" role="button">今すぐ始める</a></p>
</div>
<div class="box4">
  <div class="box4-1">
    <div class="merit">
      <a href="#">
        <h1><i class="fa fa-heart"></i> 経験ゼロの初心者向け</h1>
        <p>全10回講座の課題解決型プログラム。経験ゼロからWebエンジニアになっていただきます。</p>
      </a>
    </div>
  </div>
  <div class="box4-2">
    <div class="merit">
      <a href="#">
        <h1><i class="fa fa-television"></i>オンラインサポート付き</h1>
        <p>専用のfacebookグループ内やNitrousのコラボレーション機能を経由して随時オンラインサポート</p>
      </a>
    </div>
  </div>
  <div class="box4-3">
    <div class="merit">
      <a href="#">
        <h1><i class="fa fa-connectdevelop"></i>チームで実践「受託開発」</h1>
        <p>ひとりではなく開発チームを結成し、実ビジネスの受託開発を経験して卒業していただきます。</p>
      </a>
    </div>
  </div>
</div>
<div class="box5">
  <div class="copyright">
    <p>Copyright &copy; 2015 Dive into Code All Rights Reserved.</p>
  </div>
</div>